### PR TITLE
amogus

### PR DESCRIPTION
**Pull request by greg-el**
amogus

### CODE REVIEW

**Comment by 0xhiro** [comment]
I appreciate the PR. as much as i would love to merge this right away, is there a way to maake the code a little more readable hahaha. Maybe instead or replacing the text completely, only add an underscore and then the emoji after every variable. like ´random_ඞ´

**Comment by greg-el** [comment]
amogus :)

**Comment by 0xhiro** [comment]
Reviewing....... hang on crewmate!!!

**Comment by 0xhiro** [comment]
There have been new commits which conflict with this PR. Please fetch the latest updates and request again. thanks!

**Comment by Andrewp2** [comment]
amogus

**Comment by 0xhiro** [comment]
Looks good!

**Comment by 0xhiro** [comment]
Any further changes?

**Comment by greg-el** [comment]
good to go i think :)

**Comment by 0xhiro** [comment]
I don't know if this is gonna work, I've not done any tests or reviews, but i don't care. it looks pretty good to me, so i'm merging this without review! This PR makes me go YESS!!!!

**Pull request merged**
